import type {Metadata} from "next";
import "@/app/globals.css";
import MainLayout from "@/app/feed/main-layout";
import "bootstrap/dist/css/bootstrap.min.css"
import "@/app/feed/index.css"

export const metadata: Metadata = {
    title: "Bsky Feed",
    description: "Bsky Feed",
    // description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
        params
    }: {
        children: React.ReactNode;
        params: Promise<{ type: string }>
    }) {
    const {type} = await params;

    // Simple mapping for titles
    const titles: Record<string, string> = {
        'following': 'Following',
        'for-you': 'For You',
        'wuwa-cf': 'Wuthering Waves',
        'hatsunemiku-cf': 'Hatsune Miku',
        'touhou-cf': 'Touhou Project',
        'prsk-custom': 'Colorful Stage'
    };

    const title = titles[type] || 'Feed';
    metadata.title = `${title} | Bsky Feed`;
    metadata.description = `${title} feed`;
    return MainLayout(title, children);
}
