import type {Metadata} from "next";
import "@/app/globals.css";
import MainLayout from "@/app/feed/main-layout";
export const metadata: Metadata = {
    title: "Bsky Feed For You",
    // description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    const title = 'For You';
    // if (req.url.includes('foryou')) {
    //     console.log('Fetching For You feed');
    //     title = 'For You';
    // }
    return MainLayout(title, children);
}
