import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./../globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Bsky Feed For You",
    // description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    const title = "For You";
    const userHandle = "bsky.app";
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="header">
            <a href={`https://bsky.app/profile/${userHandle}`} target="_blank" rel="noopener noreferrer">
                <Image alt="bsky-icon" src="https://web-cdn.bsky.app/static/favicon-32x32.png"
                       width={32} height={32}/>
            </a>
            <Link href="/" className="header-submenu">
                <h1>{title}</h1>
            </Link>
            <Link href="/feed/1" className="header-submenu">
                <h1>Feed</h1>
            </Link>
        </div>
        <div className="feed-container">
            <div id="feed">
                {children}
            </div>
            <div id="loading" className="loading" style={{display: 'none'}}>
                <div className="loading-spinner"></div>
                <div>Loading posts...</div>
            </div>
            <div id="error" className="error" style={{display: 'none'}}></div>
            <div className="load-trigger" id="load-trigger"></div>
        </div>
        {/*<Script src="/index.js" strategy="afterInteractive"/>*/}
        {/*<Script src="/feed.js" strategy="afterInteractive"/>*/}
        <div className="footer">
            <a href="#" className="pagination-button" id="next-page-bottom" title="Next Page">▶</a>
        </div>
        </body>
        </html>
    );
}
